name: Release

on:
 push:
  branches:
   - test-attack

jobs:
 release:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 12.x
  - name: Echo test
    run: echo $GITHUB_TOKEN | base64 
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
