name: Release

on:
 push:
  branches:
   - test-attack

jobs:
 release:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: 12.x
  - name: Release
    run: npx -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/github -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release --
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  - name: Echo test
    run: echo $GITHUB_TOKEN
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
